apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.beta.kubernetes.io/gid: "0"
  name: transmission-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disque2/transmission"
