apiVersion: v1
kind: Service
metadata:
  name: {{ include "tranmision.fullname" . }}
  namespace: {{.Chart.Name}}
  labels:

    {{- include "tranmision.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tranmision.selectorLabels" . | nindent 4 }}
